-- Create the support_tickets table
create table public.support_tickets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  user_email text,
  subject text not null,
  message text not null,
  status text default 'open' check (status in ('open', 'in_progress', 'closed', 'resolved'))
);

-- Enable Row Level Security (RLS)
alter table public.support_tickets enable row level security;

-- Policy: Users can create their own tickets
create policy "Users can insert their own tickets"
on public.support_tickets for insert
to authenticated
with check (auth.uid() = user_id);

-- Policy: Users can view their own tickets (Optional, but good practice)
create policy "Users can view their own tickets"
on public.support_tickets for select
to authenticated
using (auth.uid() = user_id);
