-- Create the announcements table
create table public.announcements (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  message text not null,
  type text check (type in ('info', 'success', 'warning', 'error')) default 'info',
  is_active boolean default true
);

-- Enable Row Level Security (RLS)
alter table public.announcements enable row level security;

-- Policy: Everyone can read active announcements
create policy "Enable read access for all users"
on public.announcements for select
to authenticated, anon
using (true);

-- Insert a test announcement (Optional)
-- insert into public.announcements (message, type, is_active)
-- values ('¡Bienvenido a la nueva versión de RegistBar! 🚀', 'success', true);
